### PR TITLE
Only install build deps temporarily where they're needed

### PR DESCRIPTION
**Pull request by Page-**
This reduces the built image size by 27.3 MB, from 680.7 MB to 653.4 MB - I haven't had a chance to test if it actually works on a boombeastic yet though

### CODE REVIEW

**Comment by curcuz** [comment]
@Page- tested and it seems it breaks shairport

```
29.05.17 05:11:10 (+0200) shairport: shairport-sync: error while loading shared libraries: libconfig.so.9: cannot open shared object fil
e: No such file or directory
```

**Comment by Page-** [comment]
Ok, I guess it's because we only install the `-dev` libs so now that we remove them we also remove the actual libs that are installed as a byproduct, it shouldn't be too hard to fix

**Comment by arthurlutz** [comment]
Does resin support the ONBUILD for multistage builds ?

**Comment by curcuz** [comment]
@arthurlutz it does, here you can find an example: https://github.com/resin-io-playground/nodejs-multistage-docker

**Pull request closed without merging**
