### PR TITLE
Update Dockerfile.template

### PR DESCRIPTION
**Pull request by Rubines**
setuptools is outdated error

### CODE REVIEW

**Comment by Rubines** [comment]
Unfortunately the changes are stil ignored I dont know what buildscript really is executed so I can adapt ot this is super highly frustrating,...

**Comment by curcuz** [comment]
@rubines what are you talking about? Are you commiting your changes before pushing?

**Comment by Rubines** [comment]
I don't know how to push my changes to resin from a freaking fork.
git push resin patch-1 does not work.
This whole resin and git thing is like scratching your right ear with your left foot, only it is worse..

**Comment by curcuz** [comment]
Your Patch-1 is a branch, not a fork. You push it using magic git syntax: `git push resin patch-1:master`. In this context resin is not a right or left ear/foot but a simple git remote. There is nothing custom in the configuration control here, which is based on git. When you push to the resin remote, the resin cloud cross compiles whatever you pushed from your local workspace and sends the resulting docker container to all the devices belonging to your fleet. You can find more info here https://resin.io/how-it-works

**Comment by Rubines** [comment]
Hi

Thank you for your help but unfortunately this did not work, I get the error
error: src refspec patch-1 does not match any
Of course I already tried that. 

At work we use Teamviewer and before Subversion and before SourceSafe and these tools are way more straightforeward than git, at least to me. :)

**Comment by curcuz** [comment]
That error means you don't have any branch called patch-1

**Comment by Rubines** [comment]
I now restarted and cloned the "branch" from scratch but now I get 
 Updates were rejected because a pushed branch tip is behind its remote
counterpart. Check out this branch and integrate the remote changes

This tool is a developer torture device,
I give up,...

**Comment by curcuz** [comment]
This tool is for developers, period. That might be the problem here.

In your situation, I suggest appending `--force` to your last command.

**Comment by curcuz** [comment]
Also, I don't understand why you are complicating your life like this while not knowing git basics. I see you forked the repo, just clone your fork, add the resin remote, do your changes, and then ` git add . && git commit -m "my message" && git push resin master --force`

**Comment by Rubines** [comment]
>>This tool is for developers, period. That might be the problem here.
Let me remind you, your project is broken in the first place.
I would not have had all the troubles if it worked.

**Comment by curcuz** [comment]
@Rubines as I already said, I'm really sorry you are having issues pushing this software to your device. The master branch is indeed broken due to recent changes introduced in mopidy, which broke the build. As I mention several times in the blog post linked in the readme, this is a completely open-source project maintained in the free time by myself, usually during Fridays. There is no SLA, no obligation from my side except for my good will in contributing to the community when I can. I provided you easy instructions on how to workaround mopidy ( the `1.0.0-beta1` branch) and provided clear instructions on how to push local changes to resin. I pointed you to the resin docs as well. The problem I see here is that any instructions I provide, you are blocked before being able to try because of the complete lack of knowledge of git paired with what seems to me unwillingness to learn and salty comments

**Comment by Rubines** [comment]
No problem at least now I can try to fix it myself, until now my changes were ignored.
The --force command worked, thank you.

**Comment by Rubines** [comment]
I managed to fix the build script it now finally is able to compile a mopidy image without an error.
I still have to check if mopidy works tough. It is now uploding to the device which takes quite some time.

**Comment by Rubines** [comment]
Finally image uploaded and it looks like mopidy is working
an least I get OK MPD 0.19.0 when pointing my webbrowser to the mopidy port.
Afaik this was a setuptools problem which broke your project.
But as long as I dont hear any music and figure out how mopidy works I cant be sure.

**Pull request closed without merging**
